#!/bin/bash

set -euo pipefail

adduser --disabled-password --gecos "" "$USER"
echo -e "$PASSWORD\n$PASSWORD" | /usr/local/samba/bin/smbpasswd -a -s "$USER"

/usr/local/samba/sbin/smbd --log-stdout --foreground --no-process-group
